# Global settings
shell = "bash -c '{}'"
default-scheme = "base16-chalk"
preferred-schemes = ["base16-oxocarbon-dark", "base16-bright", "base16-blueish", "base16-framer", "base16-chalk", "base16-da-one-ocean", "base16-blueforest", "base16-cupertino", "base16-dracula", "base16-edge-light", "base16-tomorrow", "base16-gruvbox-light-hard", "base16-harmonic16-dark", "base16-harmonic16-light", "base16-nord-light", "base16-summerfruit-light", "base16-pinky", "base16-darkmoss", "base16-bright", "base16-evenok-dark"]

# Item configurations

# nvim works for free (due to our current config)

[[items]]
name = "tinted-terminal"
path = "https://github.com/tinted-theming/tinted-terminal"
themes-dir = "themes/alacritty"
hook = "cp \"$TINTY_THEME_FILE_PATH\" ~/.config/alacritty/colors.toml"
supported-systems = ["base16"]

[[items]]
name = "termshark"
path = "https://github.com/spencercouture/tinted-termshark.git"
themes-dir = "colors"
hook = "cp \"$TINTY_THEME_FILE_PATH\" ~/.config/termshark/themes/colors-256.toml"
supported-systems = ["base16"]

[[items]]
name = "tmux"
path = "https://github.com/spencercouture/tinted-tmux-pine.git"
themes-dir = "colors"
hook = "cp \"$TINTY_THEME_FILE_PATH\" ~/.config/colors.tmux ; tmux run 2> /dev/null && bash \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16"]
